name: mumatch
channels:
  - conda-forge
  - defaults
dependencies:
  - igl
  - joblib
  - jupyter=1.0.0
  - meshplot=0.4.0
  - numpy=1.21.2
  - pandas
  - pip=21.2.4
  - python=3.8
  - pyyaml=5.4.1
  - scikit-learn=0.24.2
  - scipy=1.7.1
  - tensorboard=2.4.1
  - tensorflow=2.4.3
  - tqdm=4.62.2
  - pip:
    - jax==0.2.12
    - jaxlib==0.1.64
    - matplotlib
    - networkx==2.6.3
    - ortools==9.0.9048
    - pymeshfix==0.15.0
    - scikit-image==0.18.3
    - vedo==2021.0.5
